#!/usr/bin/env python3
# SPDX-License-Identifier: BSD-2-Clause
"""Generate the explicit kernel import table for the external S31 radio ELF."""

from __future__ import annotations

import argparse
import pathlib
import subprocess


def undefined_symbols(nm: str, elf: pathlib.Path) -> list[str]:
    output = subprocess.check_output(
        [nm, "-u", str(elf)], text=True, encoding="utf-8"
    )
    symbols: set[str] = set()
    for line in output.splitlines():
        fields = line.split()
        if not fields:
            continue
        if len(fields) == 1:
            symbol = fields[0]
        elif fields[-2] in {"U", "w", "v"}:
            symbol = fields[-1]
        else:
            continue
        symbols.add(symbol)
    return sorted(symbols)


def render(symbols: list[str], source: pathlib.Path,
           linked_symbols: set[str]) -> str:
    lines = [
        "/* SPDX-License-Identifier: GPL-2.0-only */",
        "/* Generated by tools/gen_s31_radio_imports.py; do not edit. */",
        f"/* Source: {source.name}; imports: {len(symbols)} */",
        "",
        "\t.section .rodata.s31_fw_imports,\"a\",@progbits",
        "\t.balign 4",
        "\t.globl s31_fw_import_table",
        "\t.type s31_fw_import_table, @object",
        "s31_fw_import_table:",
    ]
    for index, symbol in enumerate(symbols):
        lines.extend(
            [
                f"\t.long .Ls31_fw_import_name_{index}",
                f"\t.long {symbol}" if symbol in linked_symbols else "\t.long 0",
            ]
        )
    lines.extend(
        [
            "\t.size s31_fw_import_table, . - s31_fw_import_table",
            "",
            "\t.globl s31_fw_import_count",
            "\t.type s31_fw_import_count, @object",
            "s31_fw_import_count:",
            f"\t.long {len(symbols)}",
            "\t.size s31_fw_import_count, 4",
            "",
            "\t.section .rodata.s31_fw_import_names,\"aMS\",@progbits,1",
        ]
    )
    for index, symbol in enumerate(symbols):
        escaped = symbol.replace("\\", "\\\\").replace('"', '\\"')
        lines.extend(
            [
                f".Ls31_fw_import_name_{index}:",
                f"\t.asciz \"{escaped}\"",
            ]
        )
    lines.append("")
    return "\n".join(lines)


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("--nm", required=True)
    parser.add_argument("--linked-symbols", type=pathlib.Path, required=True)
    parser.add_argument("elf", type=pathlib.Path)
    parser.add_argument("output", type=pathlib.Path)
    args = parser.parse_args()

    symbols = undefined_symbols(args.nm, args.elf)
    if not symbols:
        raise SystemExit(f"{args.elf}: no undefined imports found")
    linked_symbols = {
        line.strip() for line in args.linked_symbols.read_text(encoding="utf-8").splitlines()
        if line.strip() and not line.lstrip().startswith("#")
    }
    # The allowlist is shared by radio configurations.  Kconfig can remove a
    # call site (for example software AES does not need aligned calloc), so a
    # listed symbol absent from this payload is not an ABI error.  Keep the
    # allowlist entry for other configurations and emit only this ELF's actual
    # undefined-symbol intersection.
    unknown = linked_symbols.difference(symbols)
    if unknown:
        print("radio-imports: linked symbols unused by this payload: " +
              ", ".join(sorted(unknown)))
        linked_symbols.intersection_update(symbols)
    content = render(symbols, args.elf, linked_symbols)
    args.output.parent.mkdir(parents=True, exist_ok=True)
    temporary = args.output.with_suffix(args.output.suffix + ".tmp")
    temporary.write_text(content, encoding="utf-8")
    temporary.replace(args.output)
    print(f"radio-imports: {len(linked_symbols)} linked, "
          f"{len(symbols) - len(linked_symbols)} nullable -> {args.output}")


if __name__ == "__main__":
    main()
